title: "Haus voller Freunde Wiki"
remote_theme: just-the-docs/just-the-docs
color_scheme: light
description: "Das Wiki für das Haus voller Freunde"
url: https://wiki.haus-vollder-freunde.de
baseurl: ""
include:
  - _pages
just_the_docs:
  includes:
    head: head_custom.html
